# Generated by Django 3.0.6 on 2020-05-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название категории', max_length=55)),
                ('description', models.CharField(help_text='Описание', max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название', max_length=55, unique=True)),
                ('description', models.CharField(help_text='Описание', max_length=250)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('in_stock', models.BooleanField(default=True, help_text='Наличие')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
