# Generated by Django 3.0.6 on 2020-05-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200519_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='', help_text='Категория', on_delete=django.db.models.deletion.CASCADE, to='catalog.Subcategory'),
        ),
    ]
