# Generated by Django 3.0.6 on 2020-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Подкатегория', max_length=55),
        ),
    ]
