# Generated by Django 3.0.6 on 2020-05-20 06:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
    ]
