# Generated by Django 3.0.6 on 2020-05-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
