# Generated by Django 3.0.6 on 2020-05-21 21:18

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200521_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, default='', null=True, to='catalog.Category'),
        ),
    ]
