# Generated by Django 3.0.6 on 2020-05-22 12:20

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200521_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, help_text='Бренд', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, default=None, to='catalog.Category'),
        ),
    ]
