# Generated by Django 3.0.6 on 2020-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200522_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', help_text='Бренд', max_length=100),
        ),
    ]
