# Generated by Django 3.0.6 on 2020-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200522_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=100, unique=True)),
                ('description', models.TextField(help_text='описание')),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
