# Generated by Django 3.0.6 on 2020-06-05 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20200605_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={''}),
        ),
    ]
