# Generated by Django 3.0.6 on 2020-06-06 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200605_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Бренд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, default=None, help_text='Категория', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='Цена со скидкой', null=True, verbose_name='Цена со скидкой'),
        ),
    ]
