# Generated by Django 3.0.6 on 2020-06-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200606_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
