# Generated by Django 3.0.6 on 2020-06-07 10:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_delete_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Характеристики'),
        ),
    ]
