# Generated by Django 3.0.6 on 2020-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
