# Generated by Django 3.0.6 on 2020-05-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderproduct_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='count',
            new_name='quantity',
        ),
    ]
