# Generated by Django 3.0.6 on 2020-05-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200524_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ordered',
            new_name='is_ordered',
        ),
    ]
