# Generated by Django 3.0.6 on 2020-05-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200529_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_pk',
            field=models.CharField(blank=True, help_text='В каком заказе', max_length=100, null=True),
        ),
    ]
