# Generated by Django 3.0.6 on 2020-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orderproduct_order_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_pk',
            field=models.IntegerField(blank=True, help_text='В каком заказе', null=True),
        ),
    ]
