# Generated by Django 3.0.6 on 2020-05-31 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0013_auto_20200531_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addressee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='имя', max_length=100)),
                ('last_name', models.CharField(help_text='Фамилия', max_length=100)),
                ('phone', models.CharField(help_text='Телефон', max_length=100)),
                ('email', models.CharField(help_text='Почта', max_length=100)),
                ('order_pk', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='город', max_length=100)),
                ('street', models.CharField(help_text='улица', max_length=100)),
                ('home', models.CharField(help_text='дом', max_length=100)),
                ('flat', models.CharField(help_text='квартира', max_length=100)),
                ('order_pk', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_detail',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='order',
            name='addressee',
            field=models.ForeignKey(blank=True, default='', help_text='Получатель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Addressee'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, default='', help_text='Адрес доставки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.ShippingAddress'),
        ),
    ]
