# Generated by Django 3.0.6 on 2020-05-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200531_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='home',
            new_name='house',
        ),
    ]
