# Generated by Django 3.0.6 on 2020-06-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0015_auto_20200531_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressee',
            options={'verbose_name': 'Адресат', 'verbose_name_plural': 'Адресаты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказах'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставки'},
        ),
        migrations.AlterField(
            model_name='addressee',
            name='first_name',
            field=models.CharField(help_text='Имя', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressee',
            field=models.ForeignKey(blank=True, default='', help_text='Адресат', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Addressee'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(help_text='Город', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='flat',
            field=models.CharField(help_text='Квартира', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='house',
            field=models.CharField(help_text='Дома', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(help_text='Улица', max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('order_pk', models.IntegerField()),
                ('amount', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Payment'),
        ),
    ]
