# Generated by Django 3.0.6 on 2020-06-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_coupon_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
