# Generated by Django 3.0.6 on 2020-06-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_orderproduct_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created',
        ),
    ]
